package resolvers

// This file will be automatically regenerated based on the schema, any resolver
// implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.90

import (
	"context"
	"fmt"
	"log"
	"time"

	"github.com/99designs/gqlgen/graphql"
	"github.com/Yoshua-Carrera/mock-api/go-http-mock/internal/graph/model"
)

// MutateMock is the resolver for the mutateMock field.
func (r *mutationResolver) MutateMock(ctx context.Context) (*model.GenericMock, error) {
	c := graphql.GetOperationContext(ctx)
	mockUserName := r.FileLoader.ExtractHeaders(c.Headers)
	genericMockInternal, path, err := r.FileLoader.LoadFile(fmt.Sprintf("./mock/%s/%s", c.Operation.Operation, c.OperationName), mockUserName)
	if err != nil {
		log.Printf("[Graph - %s error] %s\n", c.Operation.Operation, err)
		return nil, err
	}
	if len(genericMockInternal.MockOrchestration) > 0 {
		genericMockInternal = r.Orchestration.HandleOrchestratedMock(genericMockInternal.MockOrchestration, path)
	}
	delay := genericMockInternal.MockDelay
	time.Sleep(time.Millisecond * time.Duration(delay))
	log.Printf("[Graph - %s success] Mock found and returned for mocks/%s for user %s\n", c.Operation.Operation, path, mockUserName)
	return &model.GenericMock{
		Data:  genericMockInternal.Data,
		Error: genericMockInternal.Error,
	}, nil
}

// QueryMock is the resolver for the queryMock field.
func (r *queryResolver) QueryMock(ctx context.Context) (*model.GenericMock, error) {
	c := graphql.GetOperationContext(ctx)
	mockUserName := r.FileLoader.ExtractHeaders(c.Headers)
	genericMockInternal, path, err := r.FileLoader.LoadFile(fmt.Sprintf("./mock/%s/%s", c.Operation.Operation, c.OperationName), mockUserName)
	if err != nil {
		log.Printf("[Graph - %s error] %s\n", c.Operation.Operation, err)
		return nil, err
	}
	if len(genericMockInternal.MockOrchestration) > 0 {
		genericMockInternal = r.Orchestration.HandleOrchestratedMock(genericMockInternal.MockOrchestration, path)
	}
	delay := genericMockInternal.MockDelay
	time.Sleep(time.Millisecond * time.Duration(delay))
	log.Printf("[Graph - %s success] Mock found and returned for mocks/%s for user %s\n", c.Operation.Operation, path, mockUserName)
	return &model.GenericMock{
		Data:  genericMockInternal.Data,
		Error: genericMockInternal.Error,
	}, nil
}
