package resolvers

// This file will be automatically regenerated based on the schema, any resolver
// implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.90

import (
	"context"
	"time"

	"github.com/99designs/gqlgen/graphql"
	"github.com/Yoshua-Carrera/mock-api/go-http/internal/graph/model"
)

// MutateMock is the resolver for the mutateMock field.
func (r *mutationResolver) MutateMock(ctx context.Context) (*model.GenericMock, error) {
	c := graphql.GetOperationContext(ctx)
	mockUserName := r.FileLoader.ExtractHeaders(c)
	genericMockInternal, path, err := r.FileLoader.LoadFile(c, mockUserName)
	if err != nil {
		return nil, err
	}
	if len(genericMockInternal.MockOrchestration) > 0 {
		genericMockInternal = r.Orchestration.HandleOrchestratedMock(genericMockInternal.MockOrchestration, path)
	}
	delay := genericMockInternal.MockDelay
	time.Sleep(time.Millisecond * time.Duration(delay))
	return &model.GenericMock{
		Data:  genericMockInternal.Data,
		Error: genericMockInternal.Error,
	}, nil
}

// QueryMock is the resolver for the queryMock field.
func (r *queryResolver) QueryMock(ctx context.Context) (*model.GenericMock, error) {
	c := graphql.GetOperationContext(ctx)
	mockUserName := r.FileLoader.ExtractHeaders(c)
	genericMockInternal, path, err := r.FileLoader.LoadFile(c, mockUserName)
	if err != nil {
		return nil, err
	}
	if len(genericMockInternal.MockOrchestration) > 0 {
		genericMockInternal = r.Orchestration.HandleOrchestratedMock(genericMockInternal.MockOrchestration, path)
	}
	delay := genericMockInternal.MockDelay
	time.Sleep(time.Millisecond * time.Duration(delay))
	return &model.GenericMock{
		Data:  genericMockInternal.Data,
		Error: genericMockInternal.Error,
	}, nil
}
