package resolvers

// This file will be automatically regenerated based on the schema, any resolver
// implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.90

import (
	"context"

	"github.com/99designs/gqlgen/graphql"
	"github.com/Yoshua-Carrera/mock-api/go-http/internal/graph/model"
)

// MutateMock is the resolver for the mutateMock field.
func (r *mutationResolver) MutateMock(ctx context.Context) (*model.GenericMock, error) {
	c := graphql.GetOperationContext(ctx)
	genericMock, err := r.FileLoader.LoadFile("mutation", c)
	if err != nil {
		return nil, err
	}
	return &genericMock, nil
}

// QueryMock is the resolver for the queryMock field.
func (r *queryResolver) QueryMock(ctx context.Context) (*model.GenericMock, error) {
	c := graphql.GetOperationContext(ctx)
	genericMock, err := r.FileLoader.LoadFile("query", c)
	if err != nil {
		return nil, err
	}
	return &genericMock, nil
}
