package graph

// This file will be automatically regenerated based on the schema, any resolver
// implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.90

import (
	"context"

	"github.com/Yoshua-Carrera/mock-api/go-http/internal/graph/model"
)

// MutateMock is the resolver for the mutateMock field.
func (r *mutationResolver) MutateMock(ctx context.Context) (*model.GenericMock, error) {
	mockStatusCode := int32(200)
	someData, err := r.FileLoader.LoadFile("mutation")
	if err != nil {
		return nil, err
	}
	genericMock := &model.GenericMock{
		Data:           someData,
		MockStatusCode: &mockStatusCode,
		Error:          []*model.Error{},
		MockDelay:      2000,
	}
	return genericMock, nil
}

// QueryMock is the resolver for the queryMock field.
func (r *queryResolver) QueryMock(ctx context.Context) (*model.GenericMock, error) {
	mockStatusCode := int32(200)
	someData, err := r.FileLoader.LoadFile("query")
	if err != nil {
		return nil, err
	}
	genericMock := &model.GenericMock{
		Data:           someData,
		MockStatusCode: &mockStatusCode,
		Error:          []*model.Error{},
		MockDelay:      2000,
	}
	return genericMock, nil
}

// Mutation returns MutationResolver implementation.
func (r *Resolver) Mutation() MutationResolver { return &mutationResolver{r} }

// Query returns QueryResolver implementation.
func (r *Resolver) Query() QueryResolver { return &queryResolver{r} }

type (
	mutationResolver struct{ *Resolver }
	queryResolver    struct{ *Resolver }
)
