package graph

// This file will be automatically regenerated based on the schema, any resolver
// implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.90

import (
	"context"
	"fmt"

	"github.com/Yoshua-Carrera/mock-api/go-http/internal/graph/model"
)

// MutateMock is the resolver for the mutateMock field.
func (r *mutationResolver) MutateMock(ctx context.Context) (*model.GenericMock, error) {
	panic(fmt.Errorf("not implemented: MutateMock - mutateMock"))
}

// QueryMock is the resolver for the queryMock field.
func (r *queryResolver) QueryMock(ctx context.Context) (*model.GenericMock, error) {
	panic(fmt.Errorf("not implemented: QueryMock - queryMock"))
}

// Mutation returns MutationResolver implementation.
func (r *Resolver) Mutation() MutationResolver { return &mutationResolver{r} }

// Query returns QueryResolver implementation.
func (r *Resolver) Query() QueryResolver { return &queryResolver{r} }

type mutationResolver struct{ *Resolver }
type queryResolver struct{ *Resolver }
