// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

type GenericMock struct {
	Data             string    `json:"data"`
	OrchestratedMock []*string `json:"orchestratedMock,omitempty"`
	MockStatusCode   *int32    `json:"mockStatusCode,omitempty"`
	Error            []*string `json:"error,omitempty"`
	MockDelay        string    `json:"mockDelay"`
	ErrorCode        int32     `json:"errorCode"`
}

type Mutation struct {
}

type Query struct {
}
