// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

type Error struct {
	Message string  `json:"message"`
	Code    int32   `json:"code"`
	Field   *string `json:"field,omitempty"`
}

type GenericMock struct {
	Data             map[string]any   `json:"data"`
	OrchestratedMock []map[string]any `json:"orchestratedMock,omitempty"`
	MockStatusCode   *int32           `json:"mockStatusCode,omitempty"`
	Error            []*Error         `json:"error,omitempty"`
	MockDelay        int32            `json:"mockDelay"`
}

type Mutation struct {
}

type Query struct {
}
